package com.rumantra.notification.domain;

public enum NotificationType {
  PROJECT_VALIDATED,
  PROJECT_UPDATED,
  BID_RECEIVED,
  BID_ACCEPTED,
  PAYMENT_RECEIVED,
  SUPPORT_REQUESTED,
  BIDDING_DEADLINE_REMINDER,
  PROJECT_CLOSED_NO_WINNER
}
