package com.rumantra.notification.domain;

public enum NotificationType {
  PROJECT_VALIDATED,
  PROJECT_UPDATED,
  BID_RECEIVED,
  BID_ACCEPTED,
  BID_REJECTED,
  PAYMENT_RECEIVED,
  SUPPORT_REQUESTED,
  BIDDING_DEADLINE_REMINDER,
  PROJECT_CLOSED_NO_WINNER,
  REVISION_REQUESTED,
  NEGOTIATION_DEADLINE_REMINDER,
  NEGOTIATION_EXPIRED,
  NEGOTIATION_DISPUTE_RESOLVED
}
