-- Architect education history (repeatable list: degree level, university, field of study, year).
-- Stored the same way as rmtr_architect.expertise (a JSONB list on the row) since education
-- entries are small structured objects owned entirely by the architect, not shared/queried
-- independently — a child table would add join overhead with no benefit here.
ALTER TABLE rmtr_architect ADD COLUMN education JSONB;

-- Reference list of universities offering an architecture program, used to back the
-- searchable dropdown in the architect profile education form. Indonesian universities are
-- sourced from BAN-PT "Unggul"/A-accredited program listings; international universities are
-- the QS World University Rankings by Subject 2026 (Architecture & Built Environment) top 100.
-- qs_rank is NULL for Indonesian entries (QS ranks architecture programs globally, not by
-- country) and approximate (tied band start) for QS rank 51-100 since QS does not publish an
-- exact order within that band.
CREATE TABLE rmtr_university (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    country VARCHAR(100) NOT NULL,
    city VARCHAR(150),
    is_indonesia BOOLEAN NOT NULL DEFAULT FALSE,
    qs_rank INT,
    sort_order INT NOT NULL DEFAULT 0
);

CREATE INDEX idx_university_name ON rmtr_university (LOWER(name));
CREATE INDEX idx_university_is_indonesia ON rmtr_university (is_indonesia, sort_order);

-- Indonesian universities with an architecture program (S1, many also with S2/S3)
INSERT INTO rmtr_university (name, country, city, is_indonesia, qs_rank, sort_order) VALUES
('Institut Teknologi Bandung', 'Indonesia', 'Bandung', TRUE, NULL, 1),
('Universitas Indonesia', 'Indonesia', 'Depok', TRUE, NULL, 2),
('Universitas Gadjah Mada', 'Indonesia', 'Yogyakarta', TRUE, NULL, 3),
('Institut Teknologi Sepuluh Nopember', 'Indonesia', 'Surabaya', TRUE, NULL, 4),
('Universitas Diponegoro', 'Indonesia', 'Semarang', TRUE, NULL, 5),
('Universitas Katolik Parahyangan', 'Indonesia', 'Bandung', TRUE, NULL, 6),
('Universitas Islam Indonesia', 'Indonesia', 'Yogyakarta', TRUE, NULL, 7),
('Universitas Trisakti', 'Indonesia', 'Jakarta', TRUE, NULL, 8),
('Universitas Brawijaya', 'Indonesia', 'Malang', TRUE, NULL, 9),
('Universitas Hasanuddin', 'Indonesia', 'Makassar', TRUE, NULL, 10),
('Universitas Sebelas Maret', 'Indonesia', 'Surakarta', TRUE, NULL, 11),
('Universitas Warmadewa', 'Indonesia', 'Denpasar', TRUE, NULL, 12),
('Universitas Kristen Petra', 'Indonesia', 'Surabaya', TRUE, NULL, 13),
('Universitas Bina Nusantara', 'Indonesia', 'Jakarta', TRUE, NULL, 14),
('Universitas Kristen Duta Wacana', 'Indonesia', 'Yogyakarta', TRUE, NULL, 15),
('Universitas Udayana', 'Indonesia', 'Denpasar', TRUE, NULL, 16),
('Universitas Katolik Soegijapranata', 'Indonesia', 'Semarang', TRUE, NULL, 17),
('Universitas Pancasila', 'Indonesia', 'Jakarta', TRUE, NULL, 18),
('Universitas Muhammadiyah Makassar', 'Indonesia', 'Makassar', TRUE, NULL, 19),
('Universitas Sumatera Utara', 'Indonesia', 'Medan', TRUE, NULL, 20),
('Universitas Kristen Indonesia', 'Indonesia', 'Jakarta', TRUE, NULL, 21),
('Universitas Gunadarma', 'Indonesia', 'Depok', TRUE, NULL, 22),
('Universitas Muhammadiyah Surakarta', 'Indonesia', 'Surakarta', TRUE, NULL, 23),
('Universitas Sam Ratulangi', 'Indonesia', 'Manado', TRUE, NULL, 24),
('Universitas Tarumanagara', 'Indonesia', 'Jakarta', TRUE, NULL, 25),
('Universitas Atma Jaya Yogyakarta', 'Indonesia', 'Yogyakarta', TRUE, NULL, 26),
('Universitas Pelita Harapan', 'Indonesia', 'Tangerang', TRUE, NULL, 27),
('Institut Teknologi Nasional Bandung', 'Indonesia', 'Bandung', TRUE, NULL, 28),
('Universitas Andalas', 'Indonesia', 'Padang', TRUE, NULL, 29),
('Universitas Riau', 'Indonesia', 'Pekanbaru', TRUE, NULL, 30),
('Universitas Lampung', 'Indonesia', 'Bandar Lampung', TRUE, NULL, 31),
('Universitas Mercu Buana', 'Indonesia', 'Jakarta', TRUE, NULL, 32),
('Universitas Esa Unggul', 'Indonesia', 'Jakarta', TRUE, NULL, 33),
('Universitas Tanjungpura', 'Indonesia', 'Pontianak', TRUE, NULL, 34),
('Universitas Sriwijaya', 'Indonesia', 'Palembang', TRUE, NULL, 35),
('Universitas Syiah Kuala', 'Indonesia', 'Banda Aceh', TRUE, NULL, 36),
('Institut Teknologi Sumatera', 'Indonesia', 'Lampung Selatan', TRUE, NULL, 37),
('Universitas Sultan Ageng Tirtayasa', 'Indonesia', 'Serang', TRUE, NULL, 38),
('Universitas Jember', 'Indonesia', 'Jember', TRUE, NULL, 39),
('Universitas Muhammadiyah Jakarta', 'Indonesia', 'Jakarta', TRUE, NULL, 40),
('Universitas Bung Hatta', 'Indonesia', 'Padang', TRUE, NULL, 41),
('Universitas Pendidikan Indonesia', 'Indonesia', 'Bandung', TRUE, NULL, 42),
('Universitas 17 Agustus 1945 Surabaya', 'Indonesia', 'Surabaya', TRUE, NULL, 43),
('Universitas Pembangunan Nasional Veteran Jawa Timur', 'Indonesia', 'Surabaya', TRUE, NULL, 44),
('Universitas Merdeka Malang', 'Indonesia', 'Malang', TRUE, NULL, 45),
('Universitas Malikussaleh', 'Indonesia', 'Lhokseumawe', TRUE, NULL, 46),
('Universitas Muslim Indonesia', 'Indonesia', 'Makassar', TRUE, NULL, 47);

-- International universities: QS World University Rankings by Subject 2026,
-- Architecture & Built Environment, ranks 1-100
INSERT INTO rmtr_university (name, country, city, is_indonesia, qs_rank, sort_order) VALUES
('University College London', 'United Kingdom', NULL, FALSE, 1, 1001),
('Massachusetts Institute of Technology', 'United States', NULL, FALSE, 2, 1002),
('Delft University of Technology', 'Netherlands', NULL, FALSE, 3, 1003),
('ETH Zurich', 'Switzerland', NULL, FALSE, 4, 1004),
('Manchester School of Architecture', 'United Kingdom', NULL, FALSE, 5, 1005),
('Politecnico di Milano', 'Italy', NULL, FALSE, 6, 1006),
('Harvard University', 'United States', NULL, FALSE, 7, 1007),
('National University of Singapore', 'Singapore', NULL, FALSE, 7, 1008),
('Tsinghua University', 'China', NULL, FALSE, 9, 1009),
('University of California, Berkeley', 'United States', NULL, FALSE, 10, 1010),
('École Polytechnique Fédérale de Lausanne', 'Switzerland', NULL, FALSE, 11, 1011),
('Tongji University', 'China', NULL, FALSE, 12, 1012),
('University of Cambridge', 'United Kingdom', NULL, FALSE, 13, 1013),
('University of Hong Kong', 'Hong Kong', NULL, FALSE, 14, 1014),
('RMIT University', 'Australia', NULL, FALSE, 15, 1015),
('Columbia University', 'United States', NULL, FALSE, 16, 1016),
('The University of Tokyo', 'Japan', NULL, FALSE, 17, 1017),
('Politecnico di Torino', 'Italy', NULL, FALSE, 18, 1018),
('Cornell University', 'United States', NULL, FALSE, 19, 1019),
('Universitat Politècnica de Catalunya', 'Spain', NULL, FALSE, 19, 1020),
('Hong Kong Polytechnic University', 'Hong Kong', NULL, FALSE, 21, 1021),
('Universidad Politécnica de Madrid', 'Spain', NULL, FALSE, 21, 1022),
('The University of Melbourne', 'Australia', NULL, FALSE, 23, 1023),
('Technische Universität Berlin', 'Germany', NULL, FALSE, 24, 1024),
('Technical University of Munich', 'Germany', NULL, FALSE, 25, 1025),
('University of Sheffield', 'United Kingdom', NULL, FALSE, 26, 1026),
('Nanyang Technological University', 'Singapore', NULL, FALSE, 27, 1027),
('Georgia Institute of Technology', 'United States', NULL, FALSE, 28, 1028),
('Stanford University', 'United States', NULL, FALSE, 28, 1029),
('The University of Sydney', 'Australia', NULL, FALSE, 28, 1030),
('Seoul National University', 'South Korea', NULL, FALSE, 31, 1031),
('University of California, Los Angeles', 'United States', NULL, FALSE, 32, 1032),
('UNSW Sydney', 'Australia', NULL, FALSE, 33, 1033),
('Pontificia Universidad Católica de Chile', 'Chile', NULL, FALSE, 34, 1034),
('University of Pennsylvania', 'United States', NULL, FALSE, 34, 1035),
('Aalto University', 'Finland', NULL, FALSE, 36, 1036),
('Yale University', 'United States', NULL, FALSE, 36, 1037),
('Institute of Science Tokyo', 'Japan', NULL, FALSE, 38, 1038),
('Princeton University', 'United States', NULL, FALSE, 39, 1039),
('Tianjin University', 'China', NULL, FALSE, 40, 1040),
('Università Iuav di Venezia', 'Italy', NULL, FALSE, 40, 1041),
('Southeast University', 'China', NULL, FALSE, 42, 1042),
('University of Oxford', 'United Kingdom', NULL, FALSE, 42, 1043),
('KTH Royal Institute of Technology', 'Sweden', NULL, FALSE, 44, 1044),
('TU Wien', 'Austria', NULL, FALSE, 44, 1045),
('University of Toronto', 'Canada', NULL, FALSE, 44, 1046),
('KU Leuven', 'Belgium', NULL, FALSE, 47, 1047),
('Universidade de São Paulo', 'Brazil', NULL, FALSE, 48, 1048),
('University of Michigan', 'United States', NULL, FALSE, 49, 1049),
('Cardiff University', 'United Kingdom', NULL, FALSE, 50, 1050),
('University of Technology Malaysia', 'Malaysia', NULL, FALSE, 50, 1051),
('Adelaide University', 'Australia', NULL, FALSE, 51, 1052),
('Architectural Association School of Architecture', 'United Kingdom', NULL, FALSE, 51, 1053),
('Carnegie Mellon University', 'United States', NULL, FALSE, 51, 1054),
('Chalmers University of Technology', 'Sweden', NULL, FALSE, 51, 1055),
('Eindhoven University of Technology', 'Netherlands', NULL, FALSE, 51, 1056),
('Hanyang University', 'South Korea', NULL, FALSE, 51, 1057),
('Harbin Institute of Technology', 'China', NULL, FALSE, 51, 1058),
('Istanbul Technical University', 'Turkey', NULL, FALSE, 51, 1059),
('Karlsruhe Institute of Technology', 'Germany', NULL, FALSE, 51, 1060),
('Kyoto University', 'Japan', NULL, FALSE, 51, 1061),
('Loughborough University', 'United Kingdom', NULL, FALSE, 51, 1062),
('McGill University', 'Canada', NULL, FALSE, 51, 1063),
('Middle East Technical University', 'Turkey', NULL, FALSE, 51, 1064),
('Monash University', 'Australia', NULL, FALSE, 51, 1065),
('Nanjing University', 'China', NULL, FALSE, 51, 1066),
('Newcastle University', 'United Kingdom', NULL, FALSE, 51, 1067),
('Oxford Brookes University', 'United Kingdom', NULL, FALSE, 51, 1068),
('Peking University', 'China', NULL, FALSE, 51, 1069),
('Pennsylvania State University', 'United States', NULL, FALSE, 51, 1070),
('Purdue University West Lafayette', 'United States', NULL, FALSE, 51, 1071),
('Queensland University of Technology', 'Australia', NULL, FALSE, 51, 1072),
('RWTH Aachen University', 'Germany', NULL, FALSE, 51, 1073),
('Sapienza University of Rome', 'Italy', NULL, FALSE, 51, 1074),
('Shanghai Jiao Tong University', 'China', NULL, FALSE, 51, 1075),
('Technische Universität Darmstadt', 'Germany', NULL, FALSE, 51, 1076),
('Tecnológico de Monterrey', 'Mexico', NULL, FALSE, 51, 1077),
('Texas A&M University', 'United States', NULL, FALSE, 51, 1078),
('Chinese University of Hong Kong', 'Hong Kong', NULL, FALSE, 51, 1079),
('Hong Kong University of Science and Technology', 'Hong Kong', NULL, FALSE, 51, 1080),
('London School of Economics and Political Science', 'United Kingdom', NULL, FALSE, 51, 1081),
('University of Edinburgh', 'United Kingdom', NULL, FALSE, 51, 1082),
('The University of Queensland', 'Australia', NULL, FALSE, 51, 1083),
('Universidad Nacional Autónoma de México', 'Mexico', NULL, FALSE, 51, 1084),
('Universidad Nacional de Colombia', 'Colombia', NULL, FALSE, 51, 1085),
('Universidad de Buenos Aires', 'Argentina', NULL, FALSE, 51, 1086),
('University of Chile', 'Chile', NULL, FALSE, 51, 1087),
('Universidad de Los Andes', 'Colombia', NULL, FALSE, 51, 1088),
('Universitat Politècnica de València', 'Spain', NULL, FALSE, 51, 1089),
('University of Bath', 'United Kingdom', NULL, FALSE, 51, 1090),
('University of British Columbia', 'Canada', NULL, FALSE, 51, 1091),
('University of Illinois Urbana-Champaign', 'United States', NULL, FALSE, 51, 1092),
('University of Nottingham', 'United Kingdom', NULL, FALSE, 51, 1093),
('Universidade do Porto', 'Portugal', NULL, FALSE, 51, 1094),
('University of Southern California', 'United States', NULL, FALSE, 51, 1095),
('University of Technology Sydney', 'Australia', NULL, FALSE, 51, 1096),
('The University of Texas at Austin', 'United States', NULL, FALSE, 51, 1097),
('University of Waterloo', 'Canada', NULL, FALSE, 51, 1098),
('University of Stuttgart', 'Germany', NULL, FALSE, 51, 1099),
('Yonsei University', 'South Korea', NULL, FALSE, 51, 1100);
