package com.rumantra.shared.exception;

import org.springframework.http.HttpStatus;

import lombok.Getter;

@Getter
public enum ExceptionConstants {
  BID_NOT_DRAFT("BID_NOT_DRAFT", HttpStatus.BAD_REQUEST),
  BID_NOT_FOUND("BID_NOT_FOUND", HttpStatus.NOT_FOUND),
  BID_IMAGE_NOT_FOUND("BID_IMAGE_NOT_FOUND", HttpStatus.NOT_FOUND),
  UNAUTHORIZED_BID_ACCESS("UNAUTHORIZED_BID_ACCESS", HttpStatus.FORBIDDEN),
  ALREADY_BASIC_TIER("ALREADY_BASIC_TIER", HttpStatus.CONFLICT),
  UNAUTHORIZED_ARCHITECT_ACCESS("UNAUTHORIZED_ARCHITECT_ACCESS", HttpStatus.FORBIDDEN),
  ARCHITECT_NOT_FOUND("ARCHITECT_NOT_FOUND", HttpStatus.NOT_FOUND),
  PROJECT_NOT_FOUND("PROJECT_NOT_FOUND", HttpStatus.NOT_FOUND),
  INVALID_PURCHASE_QUANTITY("INVALID_PURCHASE_QUANTITY", HttpStatus.BAD_REQUEST),
  PURCHASE_NOT_FOUND("PURCHASE_NOT_FOUND", HttpStatus.NOT_FOUND),
  UNAUTHORIZED_PURCHASE_ACCESS("UNAUTHORIZED_PURCHASE_ACCESS", HttpStatus.FORBIDDEN),
  XENDIT_PAYMENT_ERROR("XENDIT_PAYMENT_ERROR", HttpStatus.BAD_GATEWAY),
  UNAUTHORIZED_PROJECT_ACCESS("UNAUTHORIZED_PROJECT_ACCESS", HttpStatus.FORBIDDEN),
  PURCHASE_ALREADY_COMPLETED("PURCHASE_ALREADY_COMPLETED", HttpStatus.CONFLICT);

  private final String code;
  private final HttpStatus httpStatus;

  ExceptionConstants(String code, HttpStatus httpStatus) {
    this.code = code;
    this.httpStatus = httpStatus;
  }
}
