package com.rumantra.shared.exception;

import org.springframework.http.HttpStatus;

import lombok.Getter;

@Getter
public enum ExceptionConstants {
  BID_NOT_DRAFT("BID_NOT_DRAFT", HttpStatus.BAD_REQUEST),
  BID_NOT_FOUND("BID_NOT_FOUND", HttpStatus.NOT_FOUND),
  BID_IMAGE_NOT_FOUND("BID_IMAGE_NOT_FOUND", HttpStatus.NOT_FOUND),
  UNAUTHORIZED_BID_ACCESS("UNAUTHORIZED_BID_ACCESS", HttpStatus.FORBIDDEN),
  ALREADY_BASIC_TIER("ALREADY_BASIC_TIER", HttpStatus.CONFLICT),
  UNAUTHORIZED_ARCHITECT_ACCESS("UNAUTHORIZED_ARCHITECT_ACCESS", HttpStatus.FORBIDDEN),
  ARCHITECT_NOT_FOUND("ARCHITECT_NOT_FOUND", HttpStatus.NOT_FOUND),
  PROJECT_NOT_FOUND("PROJECT_NOT_FOUND", HttpStatus.NOT_FOUND),
  INVALID_PURCHASE_QUANTITY("INVALID_PURCHASE_QUANTITY", HttpStatus.BAD_REQUEST),
  PURCHASE_NOT_FOUND("PURCHASE_NOT_FOUND", HttpStatus.NOT_FOUND),
  UNAUTHORIZED_PURCHASE_ACCESS("UNAUTHORIZED_PURCHASE_ACCESS", HttpStatus.FORBIDDEN),
  XENDIT_PAYMENT_ERROR("XENDIT_PAYMENT_ERROR", HttpStatus.BAD_GATEWAY),
  UNAUTHORIZED_PROJECT_ACCESS("UNAUTHORIZED_PROJECT_ACCESS", HttpStatus.FORBIDDEN),
  PURCHASE_ALREADY_COMPLETED("PURCHASE_ALREADY_COMPLETED", HttpStatus.CONFLICT),
  ATTACHMENT_NOT_FOUND("ATTACHMENT_NOT_FOUND", HttpStatus.NOT_FOUND),
  ATTACHMENT_MODIFY_NOT_DRAFT("ATTACHMENT_MODIFY_NOT_DRAFT", HttpStatus.BAD_REQUEST),
  ATTACHMENT_EMPTY_FILE("ATTACHMENT_EMPTY_FILE", HttpStatus.BAD_REQUEST),
  ATTACHMENT_INVALID_TYPE("ATTACHMENT_INVALID_TYPE", HttpStatus.BAD_REQUEST),
  ATTACHMENT_SIZE_EXCEEDED("ATTACHMENT_SIZE_EXCEEDED", HttpStatus.BAD_REQUEST),
  PHASE_NOT_FOUND("PHASE_NOT_FOUND", HttpStatus.NOT_FOUND),
  PHASE_ALREADY_PAID("PHASE_ALREADY_PAID", HttpStatus.CONFLICT),
  PROJECT_PHASE_NOT_FOUND("PROJECT_PHASE_NOT_FOUND", HttpStatus.NOT_FOUND),
  PHASE_WRONG_STATUS("PHASE_WRONG_STATUS", HttpStatus.CONFLICT),
  PROJECT_NOT_IN_PROGRESS("PROJECT_NOT_IN_PROGRESS", HttpStatus.BAD_REQUEST),
  UNAUTHORIZED_PHASE_ACCESS("UNAUTHORIZED_PHASE_ACCESS", HttpStatus.FORBIDDEN),
  PAYOUT_FAILED("PAYOUT_FAILED", HttpStatus.BAD_GATEWAY),
  NO_REVISIONS_LEFT("NO_REVISIONS_LEFT", HttpStatus.CONFLICT),
  NO_DELIVERABLES_YET("NO_DELIVERABLES_YET", HttpStatus.CONFLICT),
  STALE_TERMS("STALE_TERMS", HttpStatus.CONFLICT),
  MISSING_REQUIRED_ACCEPTANCE("MISSING_REQUIRED_ACCEPTANCE", HttpStatus.BAD_REQUEST),
  INVALID_LEGAL_DOC_TYPE("INVALID_LEGAL_DOC_TYPE", HttpStatus.BAD_REQUEST),
  INVALID_LEGAL_LANG("INVALID_LEGAL_LANG", HttpStatus.BAD_REQUEST);

  private final String code;
  private final HttpStatus httpStatus;

  ExceptionConstants(String code, HttpStatus httpStatus) {
    this.code = code;
    this.httpStatus = httpStatus;
  }
}
